# Generated by Django 3.1.2 on 2020-10-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201018_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('company_phone', models.CharField(max_length=13)),
                ('company_email', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('company_company_image', models.FileField(upload_to='gallery/companies')),
                ('company_date_created', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='job',
            name='job_company_image',
            field=models.FileField(null=True, upload_to='gallery/job-cover-images'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='pages.company'),
        ),
    ]
