# Generated by Django 3.1.2 on 2020-10-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_blogpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
