# Generated by Django 3.1.4 on 2021-01-01 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0008_auto_20201231_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, max_length=128, null=True)),
                ('github', models.CharField(blank=True, max_length=128, null=True)),
                ('cv', models.FileField(help_text='Advisable to use your name as filename', null=True, upload_to='documents/')),
                ('avatar', models.FileField(null=True, upload_to='gallery/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
