# Generated by Django 3.1.2 on 2020-10-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('Temporary', 'Temporary')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
