# Generated by Django 3.1.2 on 2020-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contact_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('date_subscribed', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('Temporary', 'Temporary')], default='Permanent', max_length=100),
        ),
    ]
