# Generated by Django 3.1.2 on 2020-10-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='feature_image',
            field=models.FileField(null=True, upload_to='gallery/'),
        ),
    ]
